language: python
python: 3.7
install:
- pip install mkdocs
script:
- mkdocs build
deploy:
  provider: pages
  local_dir: site
  skip_cleanup: true
  github_token:
    secure: L/iBT63V7qnYXUWoNXi573SGa2STZ/i4qt6HMTjf3jALsNgaLzB4WvwOgtB/EdVO+jeDcIh3U9bonwbqYKz3nBJ9mE0KbQqww+u6wIGz/4gnuYgTZ1EZhSv3mzDUgLECvMuVjtDU6Xq/VGKUstWucEHTCzxpGPQs+Lx49bqQculc2r0NcR6wTaiYhE8UWQeBK2P/Bsw54br8B3c6Mr2PIEu/JSSw2oltArpb7eqG1dp3UzGjGD/lZBu0O+sxOos9bRpY53zYGl3m/eq/TGk7DgNEomvTfewVpLPkcZgGUQ3AgHLjxPFRxsvxAA7Y64kfKT77pw1+5HWtTiMSkqv5m4/X5JjyezUguQi3iHsZXwUPmhj3JIjh2UH+1SHEDd31wx/aNLWkWycUb9/7/AK+JFvvzs0LTk2oIN1H5N+Mh9aATvcGxcee4Z60f2QkrmnJUbjqPOd5yMUToy/k1VPDMJN0P12esx5YXwFWDsPuJzdMoFs5EgfsJhn25rHZX1vqfKIbfGkaNfNJoIQBZwN5+ha4insW9AcfLzgsem02lo3s1cSBgsUZbmrduI+kZHUZhTdYcVc272dDNZpasV/r1W3/kU0CnRilN0HeaSP8wPvOLaBV8kyT2d1b4eGpW6TlXWfznE4Qlyn+DDzHbNa1wcSNhJ3j0Y7ao5gjc/NEPMg=
